// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicBottomToolbar,
  DefaultBottomToolbarProps
} from "./plasmic/escape_room/PlasmicBottomToolbar";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { getTotalScore } from "../core/services/exam";
// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface BottomToolbarProps extends Omit<DefaultBottomToolbarProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultBottomToolbarProps altogether and have
// total control over the props for your component.
export interface BottomToolbarProps extends DefaultBottomToolbarProps {}

function BottomToolbar_(
  props: BottomToolbarProps,
  ref: HTMLElementRefOf<"div">
) {
  const [totalScore, setTotalScore] = React.useState<number>(0);

  React.useEffect(() => {
    const updateScore = () => {
      setTotalScore(getTotalScore());
    };

    // Initial load
    updateScore();

    // Listen for localStorage changes
    window.addEventListener('storage', updateScore);

    return () => {
      window.removeEventListener('storage', updateScore);
    };
  }, []);

  return <PlasmicBottomToolbar root={{ ref }} {...props} 
  totalPoints={{ 
    props: {
      children: `${totalScore}`
    }
   }}
  />;
}

const BottomToolbar = React.forwardRef(BottomToolbar_);
export default BottomToolbar;
