// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicExamRoomPcp,
  DefaultExamRoomPcpProps
} from "./plasmic/escape_room/PlasmicExamRoomPcp";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface ExamRoomPcpProps extends Omit<DefaultExamRoomPcpProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultExamRoomPcpProps altogether and have
// total control over the props for your component.
export interface ExamRoomPcpProps extends DefaultExamRoomPcpProps {}

function ExamRoomPcp_(props: ExamRoomPcpProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicExamRoomPcp to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicExamRoomPcp are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all ExamRoomPcpProps here, but feel free
  // to do whatever works for you.

  return <PlasmicExamRoomPcp root={{ ref }} {...props} />;
}

const ExamRoomPcp = React.forwardRef(ExamRoomPcp_);
export default ExamRoomPcp;
