/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7WvC14QG9b5jXarkiBh2yY
// Component: M2HdJEYFli90

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import ContainerTab from "../../ContainerTab"; // plasmic-import: ppx8EZHvc7Bt/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectcss
import sty from "./PlasmicClueTabbedContainer.module.css"; // plasmic-import: M2HdJEYFli90/css

createPlasmicElementProxy;

export type PlasmicClueTabbedContainer__VariantMembers = {};
export type PlasmicClueTabbedContainer__VariantsArgs = {};
type VariantPropType = keyof PlasmicClueTabbedContainer__VariantsArgs;
export const PlasmicClueTabbedContainer__VariantProps =
  new Array<VariantPropType>();

export type PlasmicClueTabbedContainer__ArgsType = {
  image?: React.ReactNode;
  name?: React.ReactNode;
  dob?: React.ReactNode;
  sex?: React.ReactNode;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicClueTabbedContainer__ArgsType;
export const PlasmicClueTabbedContainer__ArgProps = new Array<ArgPropType>(
  "image",
  "name",
  "dob",
  "sex",
  "children"
);

export type PlasmicClueTabbedContainer__OverridesType = {
  tabWrapper?: Flex__<"div">;
  tab1?: Flex__<"div">;
  scrollContainer?: Flex__<"div">;
};

export interface DefaultClueTabbedContainerProps {
  image?: React.ReactNode;
  name?: React.ReactNode;
  dob?: React.ReactNode;
  sex?: React.ReactNode;
  children?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicClueTabbedContainer__RenderFunc(props: {
  variants: PlasmicClueTabbedContainer__VariantsArgs;
  args: PlasmicClueTabbedContainer__ArgsType;
  overrides: PlasmicClueTabbedContainer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"tabWrapper"}
      data-plasmic-override={overrides.tabWrapper}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.tabWrapper
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__eev9P)}>
        <div className={classNames(projectcss.all, sty.freeBox__dqTc1)}>
          <div className={classNames(projectcss.all, sty.freeBox__ebUw)}>
            <ContainerTab
              className={classNames("__wab_instance", sty.containerTab__sgFhn)}
            />

            <ContainerTab
              active={true}
              className={classNames("__wab_instance", sty.containerTab__lqeAu)}
            />
          </div>
        </div>
      </div>
      <div
        data-plasmic-name={"tab1"}
        data-plasmic-override={overrides.tab1}
        className={classNames(projectcss.all, sty.tab1)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__guZoM)}>
          <div className={classNames(projectcss.all, sty.freeBox__zVB1)}>
            {renderPlasmicSlot({
              defaultContents: (
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fXnvf)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                />
              ),

              value: args.image
            })}
            <div className={classNames(projectcss.all, sty.columns__yAcUh)}>
              <div className={classNames(projectcss.all, sty.column__kNEjx)}>
                <div className={classNames(projectcss.all, sty.freeBox__ugCqt)}>
                  {renderPlasmicSlot({
                    defaultContents: "Kelvin Thompson",
                    value: args.name,
                    className: classNames(sty.slotTargetName)
                  })}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__pNWiE)}>
              <div className={classNames(projectcss.all, sty.column__uo9A)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ttXo1
                  )}
                >
                  {"DOB:"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__xjzz)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___1Xod3)}
                >
                  {renderPlasmicSlot({
                    defaultContents: "7/1/2022",
                    value: args.dob,
                    className: classNames(sty.slotTargetDob)
                  })}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__yMpMi)}>
              <div className={classNames(projectcss.all, sty.column__qf288)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0WxS
                  )}
                >
                  {"Sex:"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__psJvS)}>
                <div className={classNames(projectcss.all, sty.freeBox__hmXdx)}>
                  {renderPlasmicSlot({
                    defaultContents: "Male",
                    value: args.sex,
                    className: classNames(sty.slotTargetSex)
                  })}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__nDBb)}>
              <div className={classNames(projectcss.all, sty.column__a9En)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Bpzv
                  )}
                >
                  {"Race: "}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___4Knuy)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ptJDa
                  )}
                >
                  {"Black"}
                </div>
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ounBk
              )}
            >
              {"Today's date: 9/25/2025"}
            </div>
          </div>
          <div
            data-plasmic-name={"scrollContainer"}
            data-plasmic-override={overrides.scrollContainer}
            className={classNames(projectcss.all, sty.scrollContainer)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__yi0M2)}>
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(projectcss.all, sty.columns__fy7WK)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__d10Vm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rzqpp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ggHtG
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rJfYr
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nzbT0
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wewuw
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tQN
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__d5HEn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uSTc0
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ajRmj
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__f8C7H
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iWSnp
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__maaxb
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__cDrsc
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vwH0J
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dp3Wu
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___0ZZwm
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__szBzx
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nGpNo
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__h4VIa
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___5YXqx
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__phDjg
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mJzCn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eaj0N
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rSDvZ
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__i5AJ6
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3TB04
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ukcl4
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__u2KI2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yHt8
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eUywM
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__hzKvw
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pJpm4
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wneSe
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dVDxX
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__trm8
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wsSKe
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__cNFio
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qD6Qe
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__spQlc
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__z3IH4
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mouv1
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__otjOx
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lVyNs
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o106Y
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__z2Ujg
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dRsKc
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__p6Cig
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9JY6N
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xoAjT
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xpwDw
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qnkOp
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__okLU)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__tdse
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sgiPi
                          )}
                        >
                          {"Height/Weight: "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___0Jjgc
                          )}
                        >
                          {
                            "37.0 inches, 35.2 lbs\r\n(~70\rth\r percentile for both height and weight)"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                ),
                value: args.children
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  tabWrapper: ["tabWrapper", "tab1", "scrollContainer"],
  tab1: ["tab1", "scrollContainer"],
  scrollContainer: ["scrollContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  tabWrapper: "div";
  tab1: "div";
  scrollContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicClueTabbedContainer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicClueTabbedContainer__VariantsArgs;
    args?: PlasmicClueTabbedContainer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicClueTabbedContainer__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicClueTabbedContainer__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicClueTabbedContainer__ArgProps,
          internalVariantPropNames: PlasmicClueTabbedContainer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicClueTabbedContainer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "tabWrapper") {
    func.displayName = "PlasmicClueTabbedContainer";
  } else {
    func.displayName = `PlasmicClueTabbedContainer.${nodeName}`;
  }
  return func;
}

export const PlasmicClueTabbedContainer = Object.assign(
  // Top-level PlasmicClueTabbedContainer renders the root element
  makeNodeComponent("tabWrapper"),
  {
    // Helper components rendering sub-elements
    tab1: makeNodeComponent("tab1"),
    scrollContainer: makeNodeComponent("scrollContainer"),

    // Metadata about props expected for PlasmicClueTabbedContainer
    internalVariantProps: PlasmicClueTabbedContainer__VariantProps,
    internalArgProps: PlasmicClueTabbedContainer__ArgProps
  }
);

export default PlasmicClueTabbedContainer;
/* prettier-ignore-end */
