/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7WvC14QG9b5jXarkiBh2yY

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_2NmR93KeJ3 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: -2nmR9_3KeJ3/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_2NmR93KeJ3
});
