/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7WvC14QG9b5jXarkiBh2yY
// Component: dm8P2fnSqnl1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectcss
import sty from "./PlasmicReferencePanel.module.css"; // plasmic-import: dm8P2fnSqnl1/css

createPlasmicElementProxy;

export type PlasmicReferencePanel__VariantMembers = {
  modal:
    | "kelvinComputer"
    | "kelvinBookshelf"
    | "kelvinDiagram"
    | "kelvinBed"
    | "kelvinDoor"
    | "lamp"
    | "ivanBed"
    | "ivanScreen"
    | "ivanShelf"
    | "ivanDoor"
    | "sharese1"
    | "sharese2"
    | "sharese3"
    | "sharese4"
    | "kelvinPcp1"
    | "kelvinPcp2"
    | "kelvinPcp3"
    | "kelvinPcp4"
    | "sharesePcp1"
    | "sharesePcp2"
    | "sharesePcp3"
    | "sharesePcp4"
    | "ivanPcp1"
    | "ivanPcp2"
    | "ivanPcp3"
    | "ivanPcp4"
    | "unnamedVariant";
};
export type PlasmicReferencePanel__VariantsArgs = {
  modal?: SingleChoiceArg<
    | "kelvinComputer"
    | "kelvinBookshelf"
    | "kelvinDiagram"
    | "kelvinBed"
    | "kelvinDoor"
    | "lamp"
    | "ivanBed"
    | "ivanScreen"
    | "ivanShelf"
    | "ivanDoor"
    | "sharese1"
    | "sharese2"
    | "sharese3"
    | "sharese4"
    | "kelvinPcp1"
    | "kelvinPcp2"
    | "kelvinPcp3"
    | "kelvinPcp4"
    | "sharesePcp1"
    | "sharesePcp2"
    | "sharesePcp3"
    | "sharesePcp4"
    | "ivanPcp1"
    | "ivanPcp2"
    | "ivanPcp3"
    | "ivanPcp4"
    | "unnamedVariant"
  >;
};
type VariantPropType = keyof PlasmicReferencePanel__VariantsArgs;
export const PlasmicReferencePanel__VariantProps = new Array<VariantPropType>(
  "modal"
);

export type PlasmicReferencePanel__ArgsType = {
  children?: React.ReactNode;
  refOpen?: boolean;
};
type ArgPropType = keyof PlasmicReferencePanel__ArgsType;
export const PlasmicReferencePanel__ArgProps = new Array<ArgPropType>(
  "children",
  "refOpen"
);

export type PlasmicReferencePanel__OverridesType = {
  referencePanel?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultReferencePanelProps {
  children?: React.ReactNode;
  refOpen?: boolean;
  modal?: SingleChoiceArg<
    | "kelvinComputer"
    | "kelvinBookshelf"
    | "kelvinDiagram"
    | "kelvinBed"
    | "kelvinDoor"
    | "lamp"
    | "ivanBed"
    | "ivanScreen"
    | "ivanShelf"
    | "ivanDoor"
    | "sharese1"
    | "sharese2"
    | "sharese3"
    | "sharese4"
    | "kelvinPcp1"
    | "kelvinPcp2"
    | "kelvinPcp3"
    | "kelvinPcp4"
    | "sharesePcp1"
    | "sharesePcp2"
    | "sharesePcp3"
    | "sharesePcp4"
    | "ivanPcp1"
    | "ivanPcp2"
    | "ivanPcp3"
    | "ivanPcp4"
    | "unnamedVariant"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicReferencePanel__RenderFunc(props: {
  variants: PlasmicReferencePanel__VariantsArgs;
  args: PlasmicReferencePanel__ArgsType;
  overrides: PlasmicReferencePanel__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          refOpen: true
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "modal",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.modal
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    (
      hasVariant($state, "modal", "kelvinComputer")
        ? (() => {
            try {
              return true;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })()
        : true
    ) ? (
      <div
        data-plasmic-name={"referencePanel"}
        data-plasmic-override={overrides.referencePanel}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          sty.referencePanel,
          {
            [sty.referencePanelmodal_kelvinComputer]: hasVariant(
              $state,
              "modal",
              "kelvinComputer"
            )
          }
        )}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox, {
            [sty.freeBoxmodal_kelvinComputer]: hasVariant(
              $state,
              "modal",
              "kelvinComputer"
            )
          })}
        >
          {renderPlasmicSlot({
            defaultContents: null,
            value: args.children,
            className: classNames(sty.slotTargetChildren)
          })}
        </div>
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  referencePanel: ["referencePanel", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  referencePanel: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicReferencePanel__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicReferencePanel__VariantsArgs;
    args?: PlasmicReferencePanel__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicReferencePanel__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicReferencePanel__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicReferencePanel__ArgProps,
          internalVariantPropNames: PlasmicReferencePanel__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicReferencePanel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "referencePanel") {
    func.displayName = "PlasmicReferencePanel";
  } else {
    func.displayName = `PlasmicReferencePanel.${nodeName}`;
  }
  return func;
}

export const PlasmicReferencePanel = Object.assign(
  // Top-level PlasmicReferencePanel renders the root element
  makeNodeComponent("referencePanel"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicReferencePanel
    internalVariantProps: PlasmicReferencePanel__VariantProps,
    internalArgProps: PlasmicReferencePanel__ArgProps
  }
);

export default PlasmicReferencePanel;
/* prettier-ignore-end */
