/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7WvC14QG9b5jXarkiBh2yY
// Component: Fhh6u1WI2G9i

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectcss
import sty from "./PlasmicHotspot.module.css"; // plasmic-import: Fhh6u1WI2G9i/css

createPlasmicElementProxy;

export type PlasmicHotspot__VariantMembers = {
  size: "_50Px";
};
export type PlasmicHotspot__VariantsArgs = {
  size?: SingleChoiceArg<"_50Px">;
};
type VariantPropType = keyof PlasmicHotspot__VariantsArgs;
export const PlasmicHotspot__VariantProps = new Array<VariantPropType>("size");

export type PlasmicHotspot__ArgsType = {};
type ArgPropType = keyof PlasmicHotspot__ArgsType;
export const PlasmicHotspot__ArgProps = new Array<ArgPropType>();

export type PlasmicHotspot__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultHotspotProps {
  size?: SingleChoiceArg<"_50Px">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHotspot__RenderFunc(props: {
  variants: PlasmicHotspot__VariantsArgs;
  args: PlasmicHotspot__ArgsType;
  overrides: PlasmicHotspot__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "size",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.size
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootsize__50Px]: hasVariant($state, "size", "_50Px") }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__iy2MK, {
          [sty.freeBoxsize__50Px__iy2MKb1D4B]: hasVariant(
            $state,
            "size",
            "_50Px"
          )
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__kDhc8, {
            [sty.freeBoxsize__50Px__kDhc8B1D4B]: hasVariant(
              $state,
              "size",
              "_50Px"
            )
          })}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__lPtod, {
              [sty.freeBoxsize__50Px__lPtodb1D4B]: hasVariant(
                $state,
                "size",
                "_50Px"
              )
            })}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__zhdog, {
                [sty.freeBoxsize__50Px__zhdogB1D4B]: hasVariant(
                  $state,
                  "size",
                  "_50Px"
                )
              })}
            />
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHotspot__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHotspot__VariantsArgs;
    args?: PlasmicHotspot__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHotspot__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHotspot__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHotspot__ArgProps,
          internalVariantPropNames: PlasmicHotspot__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHotspot__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHotspot";
  } else {
    func.displayName = `PlasmicHotspot.${nodeName}`;
  }
  return func;
}

export const PlasmicHotspot = Object.assign(
  // Top-level PlasmicHotspot renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHotspot
    internalVariantProps: PlasmicHotspot__VariantProps,
    internalArgProps: PlasmicHotspot__ArgProps
  }
);

export default PlasmicHotspot;
/* prettier-ignore-end */
