/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7WvC14QG9b5jXarkiBh2yY
// Component: -K624mjsCdwd

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import BottomToolbar from "../../BottomToolbar"; // plasmic-import: 2RFJUesBV3VF/component
import InfographEdButton from "../../InfographEdButton"; // plasmic-import: TjjevRS570P0/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectcss
import sty from "./PlasmicFaculty.module.css"; // plasmic-import: -K624mjsCdwd/css

createPlasmicElementProxy;

export type PlasmicFaculty__VariantMembers = {};
export type PlasmicFaculty__VariantsArgs = {};
type VariantPropType = keyof PlasmicFaculty__VariantsArgs;
export const PlasmicFaculty__VariantProps = new Array<VariantPropType>();

export type PlasmicFaculty__ArgsType = {};
type ArgPropType = keyof PlasmicFaculty__ArgsType;
export const PlasmicFaculty__ArgProps = new Array<ArgPropType>();

export type PlasmicFaculty__OverridesType = {
  root?: Flex__<"div">;
  bottomToolbar?: Flex__<typeof BottomToolbar>;
  infographEdButton?: Flex__<typeof InfographEdButton>;
};

export interface DefaultFacultyProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFaculty__RenderFunc(props: {
  variants: PlasmicFaculty__VariantsArgs;
  args: PlasmicFaculty__ArgsType;
  overrides: PlasmicFaculty__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___5SGsm
            )}
          >
            {"Meet the Faculty"}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__pAdec)}>
            <div className={classNames(projectcss.all, sty.freeBox__nhccS)}>
              <div className={classNames(projectcss.all, sty.freeBox__vueCw)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__uR2E2)}
                  displayHeight={"150px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"150px"}
                  loading={"lazy"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__id6Fk)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__de7Zh
                    )}
                  >
                    {"Joy Chang"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7Ddye
                    )}
                  >
                    {"MD, MS"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vvXdj
                )}
              >
                {
                  "Joy Chang, MD, MS is an Assistant\r Professor of Medicine in the Division\r\nof Gastroenterology at the University\r of Michigan in Ann Arbor.\r\n\nShe specializes in caring for patients\r with eosinophilic GI diseases and is a\r member of the Esophageal Diseases Program at the University of Michigan.\rDr. Chang\u2019s research interests focus\ron patient and physician preferences \rand decision making in EoE care.\n"
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__inIMh)}>
              <div className={classNames(projectcss.all, sty.freeBox__fDgO)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___8Ddt)}
                  displayHeight={"150px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"150px"}
                  loading={"lazy"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__cpIfy)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pV7Rx
                    )}
                  >
                    {"Nirmala Prabu Gonsalves"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__v1ELd
                    )}
                  >
                    {"MD"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ivtbU
                )}
              >
                {
                  "Nirmala Prabu Gonsalves, MD, serves \ras Professor of Medicine in the\r Division of Gastroenterology & \rHepatology at Northwestern University Feinberg School of Medicine and is a member of\r Northwestern\u2019s Esophageal Center.\r \n\nHer research career has been\r dedicated to improving the care of\r patients with eosinophilic\r gastrointestinal diseases (EGIDs). Her\r clinical experiences with EGIDs have\r shaped the overarching research \rgoals that include identifying novel\r treatments and determining the best\rmethods to measure disease activity."
                }
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__n5M7B)}>
              <div className={classNames(projectcss.all, sty.freeBox__lZ3YK)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lOuMs)}
                  displayHeight={"150px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"150px"}
                  loading={"lazy"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__jYn2B)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___844Ap
                    )}
                  >
                    {"Calies Menard-Katcher"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__du2Si
                    )}
                  >
                    {"MD, MSc"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__o2Eoe
                )}
              >
                {
                  "Calies Menard-Katcher, MD, MSc is an\r Associate Professor in the Department \rof Pediatrics at Children\u2019s Hospital\r Colorado in Aurora, CO.\r \n\nHer research focuses on the natural\r history of EoE, particularly with \rattention to development of abnormal\r esophageal function and structure."
                }
              </div>
            </div>
          </div>
          <BottomToolbar
            data-plasmic-name={"bottomToolbar"}
            data-plasmic-override={overrides.bottomToolbar}
            className={classNames("__wab_instance", sty.bottomToolbar)}
          />

          <InfographEdButton
            data-plasmic-name={"infographEdButton"}
            data-plasmic-override={overrides.infographEdButton}
            className={classNames("__wab_instance", sty.infographEdButton)}
            onClick={async event => {
              const $steps = {};

              $steps["updateStateVariable"] = true
                ? (() => {
                    const actionArgs = {};
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;
                      undefined;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateStateVariable"] != null &&
                typeof $steps["updateStateVariable"] === "object" &&
                typeof $steps["updateStateVariable"].then === "function"
              ) {
                $steps["updateStateVariable"] =
                  await $steps["updateStateVariable"];
              }
            }}
            onClickSubmit={async event => {
              const $steps = {};

              $steps["goToSpecialty"] = true
                ? (() => {
                    const actionArgs = { destination: `/specialty` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToSpecialty"] != null &&
                typeof $steps["goToSpecialty"] === "object" &&
                typeof $steps["goToSpecialty"].then === "function"
              ) {
                $steps["goToSpecialty"] = await $steps["goToSpecialty"];
              }
            }}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "bottomToolbar", "infographEdButton"],
  bottomToolbar: ["bottomToolbar"],
  infographEdButton: ["infographEdButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  bottomToolbar: typeof BottomToolbar;
  infographEdButton: typeof InfographEdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFaculty__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFaculty__VariantsArgs;
    args?: PlasmicFaculty__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFaculty__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFaculty__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFaculty__ArgProps,
          internalVariantPropNames: PlasmicFaculty__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFaculty__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFaculty";
  } else {
    func.displayName = `PlasmicFaculty.${nodeName}`;
  }
  return func;
}

export const PlasmicFaculty = Object.assign(
  // Top-level PlasmicFaculty renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    bottomToolbar: makeNodeComponent("bottomToolbar"),
    infographEdButton: makeNodeComponent("infographEdButton"),

    // Metadata about props expected for PlasmicFaculty
    internalVariantProps: PlasmicFaculty__VariantProps,
    internalArgProps: PlasmicFaculty__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFaculty;
/* prettier-ignore-end */
