/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7WvC14QG9b5jXarkiBh2yY
// Component: N85BHE1JruFS

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 7WvC14QG9b5jXarkiBh2yY/projectcss
import sty from "./PlasmicWrongAnswer.module.css"; // plasmic-import: N85BHE1JruFS/css

createPlasmicElementProxy;

export type PlasmicWrongAnswer__VariantMembers = {
  modal:
    | "rm1Hs1"
    | "rm1Hs2"
    | "rm1Hs3"
    | "rm1Hs4"
    | "kelvinDoor"
    | "rm2Hs1"
    | "rm2Hs2"
    | "rm2Hs3"
    | "rm2Hs4"
    | "shareseDoor"
    | "rm3Hs1"
    | "rm3Hs2"
    | "rm3Hs3"
    | "rm3Hs4"
    | "ivanDoor"
    | "lamp"
    | "kelvinPcp1"
    | "kelvinPcp2"
    | "kelvinPcp3"
    | "kelvinPcp4"
    | "sharesePcp2"
    | "sharesePcp3"
    | "sharesePcp4"
    | "ivanPcp42"
    | "ivanPcp2"
    | "ivanPcp3"
    | "unnamedVariant";
};
export type PlasmicWrongAnswer__VariantsArgs = {
  modal?: SingleChoiceArg<
    | "rm1Hs1"
    | "rm1Hs2"
    | "rm1Hs3"
    | "rm1Hs4"
    | "kelvinDoor"
    | "rm2Hs1"
    | "rm2Hs2"
    | "rm2Hs3"
    | "rm2Hs4"
    | "shareseDoor"
    | "rm3Hs1"
    | "rm3Hs2"
    | "rm3Hs3"
    | "rm3Hs4"
    | "ivanDoor"
    | "lamp"
    | "kelvinPcp1"
    | "kelvinPcp2"
    | "kelvinPcp3"
    | "kelvinPcp4"
    | "sharesePcp2"
    | "sharesePcp3"
    | "sharesePcp4"
    | "ivanPcp42"
    | "ivanPcp2"
    | "ivanPcp3"
    | "unnamedVariant"
  >;
};
type VariantPropType = keyof PlasmicWrongAnswer__VariantsArgs;
export const PlasmicWrongAnswer__VariantProps = new Array<VariantPropType>(
  "modal"
);

export type PlasmicWrongAnswer__ArgsType = {};
type ArgPropType = keyof PlasmicWrongAnswer__ArgsType;
export const PlasmicWrongAnswer__ArgProps = new Array<ArgPropType>();

export type PlasmicWrongAnswer__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultWrongAnswerProps {
  modal?: SingleChoiceArg<
    | "rm1Hs1"
    | "rm1Hs2"
    | "rm1Hs3"
    | "rm1Hs4"
    | "kelvinDoor"
    | "rm2Hs1"
    | "rm2Hs2"
    | "rm2Hs3"
    | "rm2Hs4"
    | "shareseDoor"
    | "rm3Hs1"
    | "rm3Hs2"
    | "rm3Hs3"
    | "rm3Hs4"
    | "ivanDoor"
    | "lamp"
    | "kelvinPcp1"
    | "kelvinPcp2"
    | "kelvinPcp3"
    | "kelvinPcp4"
    | "sharesePcp2"
    | "sharesePcp3"
    | "sharesePcp4"
    | "ivanPcp42"
    | "ivanPcp2"
    | "ivanPcp3"
    | "unnamedVariant"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicWrongAnswer__RenderFunc(props: {
  variants: PlasmicWrongAnswer__VariantsArgs;
  args: PlasmicWrongAnswer__ArgsType;
  overrides: PlasmicWrongAnswer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "modal",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.modal
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootmodal_rm1Hs1]: hasVariant($state, "modal", "rm1Hs1") }
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__qzTAu
        )}
      >
        {"You are incorrect."}
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__k4WFz
        )}
      >
        {"Try again!"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWrongAnswer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWrongAnswer__VariantsArgs;
    args?: PlasmicWrongAnswer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicWrongAnswer__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicWrongAnswer__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicWrongAnswer__ArgProps,
          internalVariantPropNames: PlasmicWrongAnswer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWrongAnswer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWrongAnswer";
  } else {
    func.displayName = `PlasmicWrongAnswer.${nodeName}`;
  }
  return func;
}

export const PlasmicWrongAnswer = Object.assign(
  // Top-level PlasmicWrongAnswer renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicWrongAnswer
    internalVariantProps: PlasmicWrongAnswer__VariantProps,
    internalArgProps: PlasmicWrongAnswer__ArgProps
  }
);

export default PlasmicWrongAnswer;
/* prettier-ignore-end */
